#theme: minima
title: author-y's HomePage
description: 自作PDF，メモ置き場
repository: author-y/author-y.github.io
remote_theme: jekyll/minima

plugins:
  - jekyll-last-modified-at

include:
  - _sass
  - assets