theme: minima
title: author-y's HomePage
description: 自作PDF，メモ置き場
repository: author-y/author-y.github.io

plugins:
  - jekyll-last-modified-at

# Optional. The default date format, used if none is specified in the tag.
last-modified-at:
    date-format: '%d-%b-%y'
